# Generated by Django 3.0.7 on 2020-07-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pembeli', models.CharField(max_length=25)),
                ('nama_hewan', models.CharField(max_length=25)),
                ('nama_toko', models.CharField(max_length=25)),
                ('jumlah_pesan', models.CharField(max_length=7)),
                ('harga_hewan', models.IntegerField()),
            ],
        ),
    ]
