# Generated by Django 3.0.7 on 2020-07-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_auto_20200710_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='harga_pesan',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='slug_hewan',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
