# Generated by Django 3.0.7 on 2020-07-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_auto_20200710_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='total_pesan',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
