# Generated by Django 3.0.7 on 2020-07-11 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_checkout_total_pesan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='checkout',
            new_name='pembeli_unconfirm',
        ),
    ]
