# Generated by Django 3.0.7 on 2020-07-11 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0006_auto_20200711_1504'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pembeli_confirm',
        ),
    ]
