# Generated by Django 3.0.7 on 2020-07-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0007_delete_pembeli_confirm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pembeli_unconfirm',
            old_name='kode_id',
            new_name='kodein',
        ),
    ]
