# Generated by Django 3.0.7 on 2020-07-11 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0008_auto_20200711_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pembeli_unconfirm',
            old_name='kodein',
            new_name='kode',
        ),
    ]
