# Generated by Django 3.0.7 on 2020-07-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0010_auto_20200711_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembeli_unconfirm',
            name='status_pembelian',
            field=models.CharField(choices=[('Belum Dibayar', 'Belum Dibayar'), ('Pending', 'Pending'), ('Konfirmasi', 'Konfirmasi')], default='Belum Dibayar', max_length=20),
        ),
    ]
