# Generated by Django 3.0.7 on 2020-07-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0011_pembeli_unconfirm_status_pembelian'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembeli_unconfirm',
            name='slug_toko',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
