# Generated by Django 3.0.7 on 2020-07-11 15:16

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('details', '0007_delete_pembeli_confirm'),
    ]

    operations = [
        migrations.CreateModel(
            name='pembeli_confirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akun_pembeli', models.CharField(max_length=25)),
                ('nama_penerima', models.CharField(max_length=25)),
                ('telp_penerima', models.CharField(max_length=25)),
                ('kota_penerima', models.CharField(max_length=50)),
                ('provinsi_penerima', models.CharField(max_length=50)),
                ('upload_pembayaran', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='avatar/'), upload_to='')),
                ('kode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='details.pembeli_unconfirm')),
            ],
        ),
    ]
