# Generated by Django 3.0.7 on 2020-07-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembeli_confirm',
            name='alamat_penerima',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
