# Generated by Django 3.0.7 on 2020-07-11 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_pembeli_confirm_alamat_penerima'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembeli_confirm',
            name='akun_pembeli',
        ),
    ]
