# Generated by Django 3.0.7 on 2020-07-11 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200711_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pembeli_confirm',
            old_name='kodein',
            new_name='kodein_id',
        ),
    ]
