# Generated by Django 3.0.7 on 2020-07-13 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0010_auto_20200711_1815'),
        ('user', '0006_auto_20200713_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembeli_confirm',
            name='kodein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.pembeli_unconfirm'),
        ),
    ]
