# Generated by Django 3.0.7 on 2020-07-13 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0010_auto_20200711_1815'),
        ('user', '0007_auto_20200713_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembeli_confirm',
            name='status_pembelian',
            field=models.CharField(choices=[('Belum Dibayar', 'Belum Dibayar'), ('Pending', 'Pending'), ('Konfirmasi', 'Konfirmasi')], default='Belum Dibayar', max_length=20),
        ),
        migrations.AlterField(
            model_name='pembeli_confirm',
            name='kodein',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='details.pembeli_unconfirm'),
        ),
    ]
