# Generated by Django 3.0.7 on 2020-07-13 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200713_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembeli_confirm',
            name='status_pembelian',
        ),
    ]
