# Generated by Django 3.0.7 on 2020-07-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_pembeli_confirm_status_pembelian'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembeli_confirm',
            name='nama_toko',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pembeli_confirm',
            name='alamat_penerima',
            field=models.CharField(max_length=1000),
        ),
    ]
